server:
  port: 9001
  servlet:
    context-path: /config

spring:
  application:
    name: renren-config-server
  #环境 dev|test|prod
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
    basename: i18n/messages_common
  cloud:
    nacos:
      discovery:
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
        server-addr: ${nacos-host:nacos-host}:${nacos-port:8848}
        #nacos的命名空间ID，默认是public
        namespace: ${nacos-namespace:}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: RENREN_CLOUD_GROUP
        file-extension: yaml
        #指定共享配置，且支持动态刷新
        ext-config:
          - data-id: datasource.yaml
            group: ${spring.cloud.nacos.config.group}
            refresh: true
          - data-id: common.yaml
            group: ${spring.cloud.nacos.config.group}
            refresh: true
